# Generated by Django 4.2.7 on 2023-11-27 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraccount",
            name="first_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="useraccount",
            name="last_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
